機能要件の実装
SoichiroInagaki/tasks_app_front pull request #1
Opened 2024-09-13 09:00 UTC by SoichiroInagaki

要件定義書で求められている機能を実装し、UIの整備まで行いました。
新規タスク追加用ダイアログ内でDateTimePickerの表示コンポーネントが見切れてしまう点・タスク後、更新前の完了状態が引き継がれてしまう点はレビュー対応時に修正するため、手をつけていません。

2024-09-17 05:34 UTC, hikaru-onishi requested changes

2024-09-17 05:34 UTC, hikaru-onishi commented on src/components/DeleteDialog.tsx
> +  })
Custom Hooksとして、別ファイルに定義するようにして下さい。

2024-09-17 05:34 UTC, hikaru-onishi commented on src/components/EditingTaskItem.tsx
> +  });
Custom Hooksとして、別ファイルに定義するようにして下さい。

2024-09-17 05:34 UTC, hikaru-onishi commented on src/components/NewTask.tsx
> +  });
Custom Hooksとして、別ファイルに定義するようにして下さい。

2024-09-17 05:34 UTC, hikaru-onishi commented on src/components/TasksList.tsx
> +  });
Custom Hooksとして、別ファイルに定義するようにして下さい。

2024-09-17 05:34 UTC, hikaru-onishi commented on src/components/TasksList.tsx
> +  const [activeId, setActiveId] = useState(-1);
-1が未選択を表す便宜的なIDなら、定数などで定義してその意味を明示するようにして下さい。（マジックナンバーはないようにする）
もしくは、初期値をundefinedとして、undefinedをもって未選択を表現するといいと思います。
useState<number | undefined>(undefined);

2024-09-17 05:34 UTC, hikaru-onishi commented on src/config/requestConfig.tsx
> +};
task一覧のqueryKeyを表現する名前に変更した上で、keyの配列を定義するようにするとシンプルになると思います。

2024-09-17 05:34 UTC, hikaru-onishi commented on src/components/TaskItem.tsx
> +  });
Custom Hooksとして、別ファイルに定義するようにして下さい。

2024-09-17 06:33 UTC, SoichiroInagaki commented on src/components/TasksList.tsx
> +  const [activeId, setActiveId] = useState(-1);
stateの型をnumber | undefined型とし、必要に応じてstateをundefinedにsetする形でマジックナンバーを削除しました。

2024-09-17 06:45 UTC, SoichiroInagaki commented on src/config/requestConfig.tsx
> +};
「tasksListQueryKey」という名前で、keyの文字列を格納した配列に定義し直しました。

2024-09-17 08:06 UTC, SoichiroInagaki commented on src/components/DeleteDialog.tsx
> +  })
カスタムフック「useDeleteTask」を作成します。

2024-09-18 01:20 UTC, SoichiroInagaki commented on src/components/EditingTaskItem.tsx
> +  });
カスタムフック「useUpdateTask」を作成しました。

2024-09-18 02:14 UTC, SoichiroInagaki commented on src/components/NewTask.tsx
> +  });
カスタムフック「useCreateTask」を作成しました。

2024-09-18 04:13 UTC, SoichiroInagaki commented on src/components/TasksList.tsx
> +  });
カスタムフック「useTasksList」を作成しました。

2024-09-18 04:52 UTC, SoichiroInagaki commented on src/components/TaskItem.tsx
> +  });
カスタムフック「useUpdateTask」を扱うようにしました。

2024-09-18 07:15 UTC, hikaru-onishi commented
純粋なtsファイルがtsx拡張子になっているので、tsに直して下さい。

2024-09-20 01:26 UTC, hikaru-onishi approved these changes
対応ありがとうございます。マージしてOKです。

2024-09-20 01:31 UTC, merged